export const French = {

  selectTxt: "Bienvenue",
  selectDes: "Veuillez sélectionner votre rôle pour continuer",
  regular: "Régulateur",
  driver: 'Conducteur',
  emailPlcaholder: "Adresse email",
  passPlace: "Mot de passe",
  forgotlink: "Votre mot de passe oublié?",
  loginbtn: "Se connecter",
  signuplink: 'Vous n’avez pas de compte ? S’inscrire',
  or: 'OU',
  registerTitle: 'Créez votre compte.',
  loginLink: 'Vous avez un compte? Se connecter',
  cPasswordPlac: 'Mot de passe confimr',
  telephonePlace: "Numéro de téléphone",
  namePlca: "Nom",
  surnamePlca: "Prenom",
  resetTitle: "Réinitialisation du mot de passe",
  resetDes: "Veuillez mettre votre e-mail pour réinitialiser votre mot de passe",
  email: "E-mail",
  sms: "SMS",
  submit: "Soumettre",
  otpTitle: "Vérifiez votre courrier",
  otpDes: "Veuillez mettre votre numéro de mobile pour réinitialiser votre mot de passe",
  createPasTitle: "Créer un nouveau mot de passe",
  createPassDes: "Votre nouveau mot de passe doit être différent des mots de passe utilisés précédents.",
  drawerTitle: "Arc-en-ciel polyclinique",
  drawerDes: "@Arc-en-ciel",
  homeTab1: "À planifier",
  homeTab2: "En cours",
  homeTab3: "Complété",
  detail: "Détail",
  localization: "Localisation",
  newTrip: "Nouveau voyage",

  patientScreenTitle: "Répertoire",
  patientTab1: "Patient",
  patientTab2: "Chauffeurs",
  patientTab3: "Contrats",
  searchPlacholder: "Recherche",
  patientNamePlaceholder: "Nom du patient",
  dateTimePlaceholder: "Date / heure",
  tripTypePlaceholder: "Aller simple ou aller-retour",
  departureAddressPlaceholder: "Adresse de départ",
  arrivalAddressPlaceholder: "Adresse d’arrivée",
  tripReasonPlaceholder: "Raison du voyage",
  driverPlaceholder: "Conducteur",
  transportTypePlaceholder: "Type de transport",
  notesPlaceholder: "Notes",
  reminderCheckboxLabel: "Boîte de coie pour l'envoi de rappel",
  addPatient: "Ajouter un patient",
  addDriver: "Ajouter Chauffeurs",
  addContract: "Ajouter Contrats",
  addAContract: "Ajouter un Contrats",
  addADriver: "Ajouter un Chauffeurs",
  nomPatient: "Nom du patient",
  nir: "NIR",
  scan: "Scan",
  dateOfBirth: "Date De Naissance",
  phoneNumber: "Téléphone",
  mutuelle: "Mutuelle",
  patientAddress: "Adresse Patient",
  amcNumber: "Numéro AMC",
  notes: "Notes",
  mutuelleAddress: "Adresse Mutuelle",
  address: "Adresse",
  art80: "Art 80",
  medical: 'Medical',
  Assistance: "Assistance",
  texiPayment: "Taxi Paytent",
  contractDes: 'Types De Contrats De Transport :',
  planning: "Planning",
  Attribuer: "Attribuer un chauffeur",
  successTitle: "Assigné avec succès",
  succesDes: "Le voyage a été créé avec succès",
  successDes2: "Conducteur non sélectionné, attribuez-en un.",
  done: "Dos",

  // Billng

  Billing: "Facturation",
  Tous: "Tous",
  BTreçu: "BT reçu",
  BTmanquant: "BT manquant",
  Manquant: "Manquant",
  cv: "CV",
  Complet: "Complet",
  cardTitle: "Cooper Lipshutz Dentaire",

  // Setting
  setting: "Paramètre",
  settingTitle: "Paramètres de l'application",
  language: "Langue",
  notification: "Notification",
  settingTitle2: "Paramètres du compte",
  personalInfo: "Information personnelle",
  changePass: "Changer le mot de passe",
  english: "English",
  french: "Français",
  oldPass: "Ancien mot de passe",
  newPass: "Nouveau mot de passe",
  confirmNewPass: "Mot de passe confimr",
  update: "Mise à jour",
  carte: "Carte"

};